<?php
return [
    'SKILL' => [
        'HTML' => 'HTML',
        'CSS' => 'CSS',
        'Boostrap' => 'Boostrap',
        'JQuery' => 'JQuery',
        'JSon' => 'JSon',
        'GitHub' => 'GitHub',
        'GitLab' => 'GitLab',
        'MySql' => 'MySql',
        'C++' => 'C++',
        'Php' => 'Php',
        'Symfony' => 'Symfony',
        'CakePHP' => 'CakePHP',
        'Codeigniter' => 'Codeigniter',
        'Laravel' => 'Laravel',
        'Python' => 'Python',
        'Django' => 'Django',
        'Java' => 'Java',
        'Android' => 'Android',
        'Flutter' => 'Flutter',
        'ReactJs' => 'ReactJs',
        'WordPress' => 'WordPress',
        'DataScience' => 'DataScience',
        'Kotlin' => 'Kotlin',
        '.Net' => '.Net',
    ],

    'TECHNOLOGY' => [
        'C++' => 'C++',
        'Php' => 'Php',
        'Symfony' => 'Symfony',
        'CakePHP' => 'CakePHP',
        'Codeigniter' => 'Codeigniter',
        'Laravel' => 'Laravel',
        'Python' => 'Python',
        'Django' => 'Django',
        'Java' => 'Java',
        'Android' => 'Android',
        'Flutter' => 'Flutter',
        'ReactJs' => 'ReactJs',
        'WordPress' => 'WordPress',
        'DataScience' => 'DataScience',
        'Kotlin' => 'Kotlin',
        '.Net' => '.Net',
    ],

    'DESTINATION' => [
        'Web-Developer' => 'Web-Developer',
        'App-Developer' => 'App-Developer',
        'BackEnd-Developer' => 'BackEnd-Developer',
        'Php-Developer' => 'Php-Developer',
        'Laravel-Developer' => 'Laravel-Developer',
        'Java-Developer' => 'Java-Developer',
        'Python-Developer' => 'Python-Developer',
    ],

    'COLOR' => [
        'Primary' => 'bg-primary',
        'Success' => 'bg-success',
        'Info' => 'bg-info',
        'Warning' => 'bg-warning',
        'Danger' => 'bg-danger',
        'Dark' => 'bg-dark',
    ],

    'GRADE' => [
        'A' => 'a',
        'B' => 'b',
        'C' => 'c',
        'D' => 'd',
        'E' => 'e',
        'F' => 'f',
    ],

];
